### ISSUE TITLE
As a novice user, I want to search for nearby astronomical objects so that I can align to them.

### ISSUE THREAD

**Issue by austinbdill** [edwardfoyle/junior-design#3]
- [x] Query database based on coordinates for nearby objects
- [x] Display suggestions for nearby objects
- [x] Allow for search based on name, type, etc. (?)
- [x] Send object coordinates to telescope for alignment

**Comment by austinbdill** [comment]
Made progress on using web scraping to search database based on coordinates. Having trouble sifting through html to pull out relevant coordinates.

**Comment by austinbdill** [comment]
Still unable to find reasonable way to pull from tables in web scraping. Really wish there was an API for this.

**Comment by austinbdill** [comment]
Hey, since we decided to build the database, I assigned Ed and Megan to this issue, since you guys are the only ones that know anything about databases. Here's the website again: http://simbad.u-strasbg.fr/simbad/

**Comment by tyang82** [comment]
completed - error checking for non-existing stars
